language: php
php:
  - 5.3
  - 5.5
env:
  - MAGENTO=1.8.1.0
  - MAGENTO=1.9.1.0
before_install:
  - mkdir test-root/
install:
  - composer install --dev
before_script:
  - CURR_DIR=$(pwd)
  - vendor/bin/mage-ci install test $MAGENTO magento_test -c -t -r http://mage-ci.ecomdev.org
script:
  - vendor/bin/phpunit
